version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/usr/app
    container_name: bimm-server
    environment:
      - REDIS_URL=redis://redis-cache
      - PORT=4000
      - LIMIT_API_TO=5
    ports:
      - '4000:4000'
    command: npm run start

  redis-server:
    image: 'redis'
    container_name: redis-cache
    ports:
      - 6379:6379
